//====================================================================================================================================================
// Copyright 2025 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.25.00.08
// Generated on Sunday, January 11, 2026 8:04:43 PM

#pragma once

#include <memory>
#include <string>

// FRC Includes
#include <networktables/NetworkTable.h>

#include <ctre/phoenix/motorcontrol/can/TalonSRX.h>
#include <ctre/phoenix/motorcontrol/SupplyCurrentLimitConfiguration.h>
#include "rev/SparkMax.h"
#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/controls/Follower.hpp"
#include "ctre/phoenix6/configs/Configuration.hpp"
#include "ctre/phoenix6/TalonFXS.hpp"
#include "utils/logging/signals/DragonDataLogger.h"
#include <frc/DigitalInput.h>
#include <frc/filter/Debouncer.h>
#include <ctre/phoenix6/CANcoder.hpp>
#include <ctre/phoenix6/configs/Configurator.hpp>
#include <ctre/phoenix6/signals/SpnEnums.hpp>

#include "mechanisms/base/BaseMech.h"
#include "state/StateMgr.h"
#include "state/IRobotStateChangeSubscriber.h"
#include "mechanisms/controllers/ControlData.h"
#include "state/RobotStateChanges.h"

#include "configs/RobotElementNames.h"
#include "configs/MechanismConfigMgr.h"

#include "RobotIdentifier.h"

class BaseMechTesting : public BaseMech, public StateMgr, public IRobotStateChangeSubscriber
{
public:
	enum STATE_NAMES
	{
		STATE_OFF,
		STATE_PERCENT_OUT,
		STATE_VELOCITY_RPM,
		STATE_POSITION_IN,
		STATE_POSITION_DEG
	};

	BaseMechTesting(RobotIdentifier activeRobotId);
	BaseMechTesting() = delete;
	~BaseMechTesting() = default;

	void CreateThing3();
	void InitializeThing3();

	/// @brief Set the control constants (e.g. PIDF values).
	/// @param indentifier the motor controller usage to identify the motor
	/// @param slot position on the motor controller to set
	/// @param pid control data / constants
	virtual void SetControlConstants(RobotElementNames::MOTOR_CONTROLLER_USAGE indentifier, int slot, ControlData pid);

	/// @brief update the output to the mechanism using the current controller and target value(s)
	virtual void Update();

	void UpdateTargetTalonSRXTestPercentOut(double percentOut) { m_TalonSRXTestActiveTarget = percentOut; }
	void UpdateTargetTalonFXTestPercentOut(double percentOut)
	{
		m_TalonFXTestPercentOut.Output = percentOut;
		m_TalonFXTestActiveTarget = &m_TalonFXTestPercentOut;
	}
	void UpdateTargetTalonFXSTestPercentOut(double percentOut)
	{
		m_TalonFXSTestPercentOut.Output = percentOut;
		m_TalonFXSTestActiveTarget = &m_TalonFXSTestPercentOut;
	}
	void UpdateTargetTalonFXTestFXVelocityRPM(units::angular_velocity::turns_per_second_t velocity)
	{
		m_TalonFXTestFXVelocityRPM.Velocity = velocity;
		m_TalonFXTestActiveTarget = &m_TalonFXTestFXVelocityRPM;
	}
	void UpdateTargetTalonFXSTestFXSVelocityRPM(units::angular_velocity::turns_per_second_t velocity)
	{
		m_TalonFXSTestFXSVelocityRPM.Velocity = velocity;
		m_TalonFXSTestActiveTarget = &m_TalonFXSTestFXSVelocityRPM;
	}
	void UpdateTargetTalonFXTestFXPositionIn(units::length::inch_t position)
	{
		m_TalonFXTestFXPositionIn.Position = units::angle::turn_t(position.value());
		m_TalonFXTestActiveTarget = &m_TalonFXTestFXPositionIn;
	}
	void UpdateTargetTalonFXSTestFXSPositionIn(units::length::inch_t position)
	{
		m_TalonFXSTestFXSPositionIn.Position = units::angle::turn_t(position.value());
		m_TalonFXSTestActiveTarget = &m_TalonFXSTestFXSPositionIn;
	}
	void UpdateTargetTalonFXTestFXPositionDeg(units::angle::turn_t position)
	{
		m_TalonFXTestFXPositionDeg.Position = position;
		m_TalonFXTestActiveTarget = &m_TalonFXTestFXPositionDeg;
	}
	void UpdateTargetTalonFXSTestFXSPositionDeg(units::angle::turn_t position)
	{
		m_TalonFXSTestFXSPositionDeg.Position = position;
		m_TalonFXSTestActiveTarget = &m_TalonFXSTestFXSPositionDeg;
	}

	virtual bool IsAtMinPosition(RobotElementNames::MOTOR_CONTROLLER_USAGE identifier) const;
	virtual bool IsAtMaxPosition(RobotElementNames::MOTOR_CONTROLLER_USAGE identifier) const;

	void CreateAndRegisterStates();
	void Cyclic();
	void RunCommonTasks() override;
	// void DataLog() override;

	RobotIdentifier getActiveRobotId() { return m_activeRobotId; }

	ctre::phoenix::motorcontrol::can::TalonSRX *GetTalonSRXTest() const { return m_TalonSRXTest; }
	rev::spark::SparkMax *GetSparkMaxBrushedTest() const { return m_SparkMaxBrushedTest; }
	ctre::phoenix6::hardware::TalonFX *GetTalonFXTest() const { return m_TalonFXTest; }
	ctre::phoenix6::hardware::TalonFXS *GetTalonFXSTest() const { return m_TalonFXSTest; }
	bool GetdigitalInputTestState() const { return m_DigitalInputTestIsInverted ? !m_DigitalInputTest->Get() : m_DigitalInputTest->Get(); }
	ctre::phoenix6::hardware::CANcoder *GetCANcoderTest() const { return m_CANcoderTest; }
	ControlData *GetPercentOut() const { return m_PercentOut; }
	ControlData *GetFXVelocityRPM() const { return m_FXVelocityRPM; }
	ControlData *GetFXSVelocityRPM() const { return m_FXSVelocityRPM; }
	ControlData *GetFXPositionIn() const { return m_FXPositionIn; }
	ControlData *GetFXSPositionIn() const { return m_FXSPositionIn; }
	ControlData *GetFXPositionDeg() const { return m_FXPositionDeg; }
	ControlData *GetFXSPositionDeg() const { return m_FXSPositionDeg; }

	static std::map<std::string, STATE_NAMES> stringToSTATE_NAMESEnumMap;

	void SetCurrentState(int state, bool run) override;

protected:
	RobotIdentifier m_activeRobotId;
	std::string m_ntName;

	ControlData *GetControlData(std::string name) override;

private:
	std::unordered_map<std::string, STATE_NAMES> m_stateMap;

	ctre::phoenix::motorcontrol::can::TalonSRX *m_TalonSRXTest;
	rev::spark::SparkMax *m_SparkMaxBrushedTest;
	ctre::phoenix6::hardware::TalonFX *m_TalonFXTest;
	ctre::phoenix6::hardware::TalonFXS *m_TalonFXSTest;
	frc::DigitalInput *m_DigitalInputTest;
	bool m_DigitalInputTestIsInverted;
	ctre::phoenix6::hardware::CANcoder *m_CANcoderTest;
	ControlData *m_PercentOut;
	ControlData *m_FXVelocityRPM;
	ControlData *m_FXSVelocityRPM;
	ControlData *m_FXPositionIn;
	ControlData *m_FXSPositionIn;
	ControlData *m_FXPositionDeg;
	ControlData *m_FXSPositionDeg;

	void InitializeTalonSRXTalonSRXTestThing3();
	void InitializeSparkMaxSparkMaxBrushedTestThing3();
	void InitializeTalonFXTalonFXTestThing3();
	void InitializeTalonFXSTalonFXSTestThing3();

	double m_TalonSRXTestActiveTarget;

	ctre::phoenix6::controls::DutyCycleOut m_TalonFXTestPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_TalonFXSTestPercentOut{0.0};
	ctre::phoenix6::controls::VelocityVoltage m_TalonFXTestFXVelocityRPM{units::angular_velocity::turns_per_second_t(0.0)};
	ctre::phoenix6::controls::VelocityVoltage m_TalonFXSTestFXSVelocityRPM{units::angular_velocity::turns_per_second_t(0.0)};
	ctre::phoenix6::controls::PositionVoltage m_TalonFXTestFXPositionIn{units::angle::turn_t(0.0)};
	ctre::phoenix6::controls::PositionVoltage m_TalonFXSTestFXSPositionIn{units::angle::turn_t(0.0)};
	ctre::phoenix6::controls::PositionVoltage m_TalonFXTestFXPositionDeg{units::angle::turn_t(0.0)};
	ctre::phoenix6::controls::PositionVoltage m_TalonFXSTestFXSPositionDeg{units::angle::turn_t(0.0)};
	ctre::phoenix6::controls::ControlRequest *m_TalonFXTestActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_TalonFXSTestActiveTarget;

	// void InitializeLogging();
};