//====================================================================================================================================================
// Copyright 2025 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.00
// Generated on Monday, January 19, 2026 3:54:42 PM

#include <string>

#include "configs/MechanismConfigThing_3.h"
#include "configs/MechanismConfigMgr.h"
#include "configs/RobotElementNames.h"
#include "utils/logging/debug/Logger.h"
#include "utils/PeriodicLooper.h"

#include <frc/Compressor.h>

using std::string;

void MechanismConfigThing_3::DefineMechanisms()
{
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("Initializing mechanism"), string("BaseMechTesting"), "");
	m_theBaseMechTesting = new BaseMechTesting(RobotIdentifier::THING_3);
	m_theBaseMechTesting->CreateThing3();
	m_theBaseMechTesting->CreateAndRegisterStates();
	m_theBaseMechTesting->InitializeThing3();
	m_theBaseMechTesting->Init(/*m_theBaseMechTesting*/);
	m_mechanismMap[MechanismTypes::MECHANISM_TYPE::BASE_MECH_TESTING] = m_theBaseMechTesting;
}

StateMgr *MechanismConfigThing_3::GetMechanism(MechanismTypes::MECHANISM_TYPE mechType)
{
	auto itr = m_mechanismMap.find(mechType);
	if (itr != m_mechanismMap.end())
	{
		return itr->second;
	}
	return nullptr;
}

void MechanismConfigThing_3::DefineLEDs()
{
}

void MechanismConfigThing_3::DefineCompressor()
{
	auto CompressorTest = new frc::Compressor(1, frc::PneumaticsModuleType::REVPH);
	CompressorTest->EnableAnalog(95_psi, 119.5_psi);
}